### ISSUE TITLE
Constraint Layout 2.0 Alpha 1 is not working with Navigation SafeArgs

### ISSUE THREAD

**Issue by rodrigosol** [googlesamples/android-ConstraintLayoutExamples#14]
Hi There,

I don't know if this is the appropriate place to report issues like that, but I could not find any other location.

It seems that something goes wrong with Navigation Safe Args when I add Constraint Layout 2.0 to my build.gradle.

My navigation arg looks like this:
```xml
 <argument
            android:name="aplicacaoId"
            app:type="integer" />
```
When I change the constraint layout to `implementation 'com.android.support.constraint:constraint-layout:2.0.0-alpha1'` Android Studio gives me the following error:
```
Output:  /nav_graph.xml:120: error: 'integer' is incompatible with attribute type (attr) enum [deltaRelative=0, parentRelative=2, pathRelative=1] [weak].
```
Thanks.

**Comment by thagikura** [comment]
Hi, thanks for filing this.

However, looks like it's not related to the sample code, but the navigation support library. I suggest you to file an issue for the [issue tracker for the support library](https://issuetracker.google.com/issues/new?component=192731&template=842428)

It's appreciated if you describe the steps on how to reproduce as detailed as possible in the issue.
(If you have an example project, that would be awesome)

Thanks.
