### ISSUE TITLE
Constraint Layout Min SDK level

### ISSUE THREAD

**Issue by RobertKeazor** [googlesamples/android-ConstraintLayoutExamples#18]
Currently constraint layout 2.0 alpha only supports a min sdk level of 18 in the support library.  Is there any plans to back port it to earlier versions , like its predecessor (1.1.1) ?

**Comment by camaelon** [comment]
Alpha 2 supports min sdk 14. We are also planning to backport the layout parts to v1 as well (in case people don't need MotionLayout).
