### ISSUE TITLE
Aspect Ratio landscape

### ISSUE THREAD

**Issue by CapitainOats** [googlesamples/android-ConstraintLayoutExamples#32]
Layout looks badly when is presented in landscape. 

![aspect_ratio_landscape](https://user-images.githubusercontent.com/17655140/45881353-37eaeb80-bdab-11e8-8998-eb435ec0e8ea.png)

**Comment by CapitainOats** [comment]
@thagikura Do you think this should be accepted issue? If so, I can help with fix. :]

**Comment by thagikura** [comment]
@CapitainOats 

Sorry for really delayed response.. 
Yes, I think it should be fixed. 
Really appreciated if you can have a look.
