### ISSUE TITLE
ViewPager with Tablayout and fragments behaves in wrong way inside motionlayout

### ISSUE THREAD

**Issue by hdakhly** [googlesamples/android-ConstraintLayoutExamples#36]
I tried to replicate the same behavior of coordinator layout with MotionLayout and i got almost the same design but i faced some issues .

My design contains Motion Layout as a parent view and inside it it contains some child views and TabLayout , ViewPager included . everything works fine with a fresh start but when you try to swipe up the viewpager and then try to scroll viewpager fragment both direction you will see empty views although the fragment is created if i tried to push the viewpager down from top fragment starts displaying right away ! also the touch events are intercepted badly while dragging up then directly scroll between fragments 

attached is my xml and motion scene 
Main XML
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.motion.widget.MotionLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layoutDescription="@xml/collapsing_toolbar"
    tools:context=".MainActivity"
    tools:showPaths="true">

    <com.google.android.material.tabs.TabLayout
        android:id="@+id/tabLayout"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/toolbar_image"
        app:tabBackground="@color/colorPrimary"
        app:tabGravity="fill"
        app:tabIndicatorColor="#ffffff"
        app:tabIndicatorHeight="4dp"
        app:tabMode="fixed">

    </com.google.android.material.tabs.TabLayout>

    <androidx.viewpager.widget.ViewPager
        android:id="@+id/viewPager"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tabLayout">

    </androidx.viewpager.widget.ViewPager>

    <ImageView
        android:id="@+id/toolbar_image"
        android:layout_width="0dp"
        android:layout_height="200dp"
        android:adjustViewBounds="true"
        android:background="@color/colorPrimary"
        android:contentDescription="@null"
        android:fitsSystemWindows="true"
        android:scaleType="center"
        android:src="@drawable/beach_huts"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <ImageView
        android:id="@android:id/home"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:contentDescription="@null"
        android:paddingStart="16dp"
        android:paddingTop="16dp"
        android:paddingEnd="16dp"
        android:paddingBottom="16dp"
        android:src="@drawable/abc_ic_ab_back_material"
        android:tint="?android:attr/textColorPrimaryInverse"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:ignore="PrivateResource" />

    <TextView
        android:id="@+id/title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="8dp"
        android:layout_marginBottom="24dp"
        android:text="@string/app_name"
        android:textColor="?android:attr/textColorPrimaryInverse"
        android:textSize="32sp"
        android:textStyle="bold"
        app:layout_constraintBottom_toBottomOf="@id/toolbar_image"
        app:layout_constraintStart_toStartOf="parent" />

</androidx.constraintlayout.motion.widget.MotionLayout>
```

Motion Scene 
<?xml version="1.0" encoding="utf-8"?>
<MotionScene xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <Transition
        app:constraintSetEnd="@id/collapsed"
        app:constraintSetStart="@id/expanded">
        <OnSwipe
            app:dragDirection="dragUp"
            app:touchAnchorId="@id/tabLayout"
            app:touchAnchorSide="top" />
    </Transition>

    <ConstraintSet android:id="@+id/expanded">
        <Constraint
            android:id="@id/toolbar_image"
            android:layout_height="200dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent">
            <CustomAttribute
                app:attributeName="imageAlpha"
                app:customIntegerValue="255" />
        </Constraint>
        <Constraint
            android:id="@id/title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="8dp"
            android:layout_marginBottom="24dp"
            android:scaleX="1.0"
            android:scaleY="1.0"
            app:layout_constraintBottom_toBottomOf="@id/toolbar_image"
            app:layout_constraintStart_toStartOf="parent" />
    </ConstraintSet>

    <ConstraintSet android:id="@+id/collapsed">
        <Constraint
            android:id="@id/toolbar_image"
            android:layout_height="?attr/actionBarSize"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent">
            <CustomAttribute
                app:attributeName="imageAlpha"
                app:customIntegerValue="0" />
        </Constraint>
        <Constraint
            android:id="@id/title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="20dp"
            android:layout_marginBottom="0dp"
            android:scaleX="0.625"
            android:scaleY="0.625"
            app:layout_constraintBottom_toBottomOf="@id/toolbar_image"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="@id/toolbar_image" />

    </ConstraintSet>

</MotionScene>

The issue is fully reproducible

**Comment by SergKlimov** [comment]
Have the same issue!
Pls give some explanation.

**Comment by Jahanvi95** [comment]
Use viewpager2 inside motionlayout and for tablayout check code https://github.com/googlesamples/android-viewpager2

**Comment by Jahanvi95** [comment]
> I tried to replicate the same behavior of coordinator layout with MotionLayout and i got almost the same design but i faced some issues .
> 
> My design contains Motion Layout as a parent view and inside it it contains some child views and TabLayout , ViewPager included . everything works fine with a fresh start but when you try to swipe up the viewpager and then try to scroll viewpager fragment both direction you will see empty views although the fragment is created if i tried to push the viewpager down from top fragment starts displaying right away ! also the touch events are intercepted badly while dragging up then directly scroll between fragments
> 
> attached is my xml and motion scene
> Main XML
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <androidx.constraintlayout.motion.widget.MotionLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:app="http://schemas.android.com/apk/res-auto"
>     xmlns:tools="http://schemas.android.com/tools"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     app:layoutDescription="@xml/collapsing_toolbar"
>     tools:context=".MainActivity"
>     tools:showPaths="true">
> 
>     <com.google.android.material.tabs.TabLayout
>         android:id="@+id/tabLayout"
>         android:layout_width="0dp"
>         android:layout_height="wrap_content"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toBottomOf="@+id/toolbar_image"
>         app:tabBackground="@color/colorPrimary"
>         app:tabGravity="fill"
>         app:tabIndicatorColor="#ffffff"
>         app:tabIndicatorHeight="4dp"
>         app:tabMode="fixed">
> 
>     </com.google.android.material.tabs.TabLayout>
> 
>     <androidx.viewpager.widget.ViewPager
>         android:id="@+id/viewPager"
>         android:layout_width="0dp"
>         android:layout_height="0dp"
>         app:layout_constraintBottom_toBottomOf="parent"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toBottomOf="@+id/tabLayout">
> 
>     </androidx.viewpager.widget.ViewPager>
> 
>     <ImageView
>         android:id="@+id/toolbar_image"
>         android:layout_width="0dp"
>         android:layout_height="200dp"
>         android:adjustViewBounds="true"
>         android:background="@color/colorPrimary"
>         android:contentDescription="@null"
>         android:fitsSystemWindows="true"
>         android:scaleType="center"
>         android:src="@drawable/beach_huts"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toTopOf="parent" />
> 
>     <ImageView
>         android:id="@android:id/home"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:contentDescription="@null"
>         android:paddingStart="16dp"
>         android:paddingTop="16dp"
>         android:paddingEnd="16dp"
>         android:paddingBottom="16dp"
>         android:src="@drawable/abc_ic_ab_back_material"
>         android:tint="?android:attr/textColorPrimaryInverse"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toTopOf="parent"
>         tools:ignore="PrivateResource" />
> 
>     <TextView
>         android:id="@+id/title"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:layout_marginStart="8dp"
>         android:layout_marginBottom="24dp"
>         android:text="@string/app_name"
>         android:textColor="?android:attr/textColorPrimaryInverse"
>         android:textSize="32sp"
>         android:textStyle="bold"
>         app:layout_constraintBottom_toBottomOf="@id/toolbar_image"
>         app:layout_constraintStart_toStartOf="parent" />
> 
> </androidx.constraintlayout.motion.widget.MotionLayout>
> ```
> 
> Motion Scene
> 
> ```
> <Transition
>     app:constraintSetEnd="@id/collapsed"
>     app:constraintSetStart="@id/expanded">
>     <OnSwipe
>         app:dragDirection="dragUp"
>         app:touchAnchorId="@id/tabLayout"
>         app:touchAnchorSide="top" />
> </Transition>
> 
> <ConstraintSet android:id="@+id/expanded">
>     <Constraint
>         android:id="@id/toolbar_image"
>         android:layout_height="200dp"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toTopOf="parent">
>         <CustomAttribute
>             app:attributeName="imageAlpha"
>             app:customIntegerValue="255" />
>     </Constraint>
>     <Constraint
>         android:id="@id/title"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:layout_marginStart="8dp"
>         android:layout_marginBottom="24dp"
>         android:scaleX="1.0"
>         android:scaleY="1.0"
>         app:layout_constraintBottom_toBottomOf="@id/toolbar_image"
>         app:layout_constraintStart_toStartOf="parent" />
> </ConstraintSet>
> 
> <ConstraintSet android:id="@+id/collapsed">
>     <Constraint
>         android:id="@id/toolbar_image"
>         android:layout_height="?attr/actionBarSize"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toTopOf="parent">
>         <CustomAttribute
>             app:attributeName="imageAlpha"
>             app:customIntegerValue="0" />
>     </Constraint>
>     <Constraint
>         android:id="@id/title"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:layout_marginStart="20dp"
>         android:layout_marginBottom="0dp"
>         android:scaleX="0.625"
>         android:scaleY="0.625"
>         app:layout_constraintBottom_toBottomOf="@id/toolbar_image"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toTopOf="@id/toolbar_image" />
> 
> </ConstraintSet>
> ```
> 
> The issue is fully reproducible

Use viewpager2 inside motionlayout and for tablayout check https://github.com/googlesamples/android-viewpager2

**Comment by hdakhly** [comment]
@Jahanvi95 viewpager doesn't solve the problem , it was a problem because of the motion layout and it is fixed in beta 2 version
