### ISSUE TITLE
MotionLayout doesn't work if child view is clickable

### ISSUE THREAD

**Issue by uOOOO** [googlesamples/android-ConstraintLayoutExamples#91]
I added ExoPlayer's PlayerView instead of ImageView to [youtubedemo](https://github.com/googlesamples/android-ConstraintLayoutExamples/tree/master/motionlayout/src/main/java/com/google/androidstudio/motionlayoutexample/youtubedemo) or changed ImageView([top_image](https://github.com/googlesamples/android-ConstraintLayoutExamples/blob/master/motionlayout/src/main/res/layout/motion_24_youtube.xml)) to clickable. And then MotionLayout swipe is not working.

Do you have any good idea without overriding any touch event methods?

Or how can I control MotionLayout precisely with overriding any touch event methods?

**Comment by treycc** [comment]
i dont know how can i find the latest version sourcecode。
i find if childview of MotionLayout intercepted the ACTIONDOWN,the MotionLayout dont process the rest touch event. this behavior dose not match the others like RecyclerView,ViewPager
the RecyclerView Fragment of demo looks like can click the item and drag the MotionLayout，i can not find the key how it works

**Comment by usama27** [comment]
same issue i'm facing.

**Comment by usama27** [comment]
I'am Facing same issue. Any solution???

**Comment by uOOOO** [comment]
I've referred to the following site..
- https://medium.com/vrt-digital-studio/picture-in-picture-video-overlay-with-motionlayout-a9404663b9e7
and implemented with exoplayer
- https://github.com/uOOOO/so-simple-android-example
